### PR TITLE
perf: optimize parse_log_file_reverse function

### PR DESCRIPTION
**Pull request by tomkarw**
Work on getting the performance back in `parse_log_file_reverse` after `rev_lines::RevLines` had to be abandoned.

### CODE REVIEW

**Comment by tomkarw** [comment]
@petrvecera Can you provide me with a sample log file? Preferably multiple, and as big as possible, it'll let me do some actual benchmarking.

I now understand what's the problem, as `Lines` iterator doesn't implement `rev()`. If the current improvement (collect once instead of growing a `Vec` multiple times), is not sufficient, I think I'll just fix the `rev_lines` crate to handle non-utf-8 content gracefully (by returning `Result<String>`, exactly how `lines()` does).

**Comment by petrvecera** [comment]
These two files should produce the errors with utf-8

[warnings.log](https://github.com/cohstats/coh3-stats-desktop-app/files/11260820/warnings.log)
[warnings (1).log](https://github.com/cohstats/coh3-stats-desktop-app/files/11260827/warnings.1.log)

The other one has 2 MB, Unfornatelly I don't have bigger ones. The warnings.log is wiped when you restart the game. So if someone starts the game and plays whole day, I assume it could grow to ~10-15 MB 

It counts with Windows OS only and the path for the logs should be 
`C:\Users\pagep\Documents\My Games\Company of Heroes 3\warnings.logs`
but I think you can try to just write tests and pass it there somehow differently

Also feel free to change anything else in the code 👍 

Thanks a lot :D

**Comment by tomkarw** [comment]
> Also feel free to change anything else in the code

I'll be happy to do that in a different PR :)

So I added a benchmark, and tested both the current `main` and my solution. There are no significant gains :disappointed: . What I'll do next is apply the benchmark to the solution with `rev_lines` (so pre utf-8 fix). If this is significantly faster, I'll fix the crate and bring it back here (while handling non-utf-8 gracefully).

**Comment by tomkarw** [comment]
Alright, I'm down to two solutions (`iter().rev()` and fixed `RevLines`), just benchmarking to make sure which is better and if there is actually any performance gain.

I need a big valid utf-8 log file, is that possible? This would let me benchmark the old pre-fix `RevLines` to make sure we get at least as good of performance.

**Comment by tomkarw** [comment]
Alright, after some detour to work on `rev_lines` crate we released `v0.3.0` there, and I use it here. It allows parsing non-utf8 lines and comes with a lot of performance upgrades.

@petrvecera Feel free to test this (I'm only 99% sure I resolved merge conflicts correctly) and merge it.

**Comment by petrvecera** [comment]
I see your MRs at https://github.com/mjc-gh/rev_lines/pulls?q=is%3Apr+is%3Aclosed , haha that's awesome! 

I am gonna test it today. I will be at my Windows system :)

**Comment by tomkarw** [comment]
> I see your MRs at https://github.com/mjc-gh/rev_lines/pulls?q=is%3Apr+is%3Aclosed , haha that's awesome!

Now you know what I do with my current abundance of free time :smile:

**Review by petrvecera — APPROVED** [review]
Looks like everythings works, let's merge 👍

**Comment by petrvecera** [comment]
Thanks  a lot ❤️

**Pull request merged**
